name = "GroupFunctions"
uuid = "187e6719-d2a6-4c17-9b39-0c99811c6bd2"
authors = ["David Amaro Alcal√° <dav1494@ciencias.unam.mx>"]
version = "0.1.5"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractAlgebra = "0.44.1"
HiGHS = "1.12.2"
JuMP = "1.23.5"
SymEngine = "0.12.0"
julia = ">= 1.6"
LinearAlgebra = ">= 1.6"
SparseArrays = ">= 1.6"
Test = ">= 1.6"
Markdown = ">= 1.6"
